
name: Java CI with Maven

on:
  push:
    branches:
      - master
      - KhanbanTask
  pull_request:
    branches:
      - master
      - KhanbanTask

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 4: Run tests
      - name: Run Tests
        run: mvn test
